import { TransactionType } from "@/lib/types";

export const transactions: TransactionType[] = [
	{
		id: "1",
		date: "2021-01-01",
		amount: 100,
		type: "expense",
		category: "food",
		description: "Food for the week",
	},
	{
		id: "2",
		date: "2021-01-02",
		amount: 200,
		type: "income",
		category: "salary",
		description: "Salary for the week on side hustle",
	},
	{
		id: "3",
		date: "2021-01-03",
		amount: 300,
		type: "expense",
		category: "entertainment",
		description: "Concert tickets",
	},
	{
		id: "4",
		date: "2021-01-04",
		amount: 400,
		type: "income",
		category: "refund",
		description: "Bob's debt payment for the week",
	},
	{
		id: "5",
		date: "2021-01-05",
		amount: 400,
		type: "income",
		category: "interest",
		description: "Interest for the week",
	},
	{
		id: "6",
		date: "2023-01-04",
		amount: 450,
		type: "saving",
		category: "saving",
		description: "Saving for the week",
	},
	{
		id: "7",
		date: "2021-01-06",
		amount: 150,
		type: "expense",
		category: "utilities",
		description: "Utilities bill for the month",
	},
	{
		id: "8",
		date: "2021-01-07",
		amount: 500,
		type: "income",
		category: "freelance",
		description: "Freelance project payment",
	},
	{
		id: "9",
		date: "2021-01-08",
		amount: 250,
		type: "expense",
		category: "transportation",
		description: "Monthly transportation pass",
	},
	{
		id: "10",
		date: "2021-01-09",
		amount: 600,
		type: "income",
		category: "bonus",
		description: "Year-end bonus",
	},
	{
		id: "11",
		date: "2021-01-10",
		amount: 700,
		type: "investment",
		category: "investments",
		description: "Stocks investment",
	},
	{
		id: "12",
		date: "2021-01-11",
		amount: 800,
		type: "transfer",
		category: "transfer",
		description: "Transfer to savings account",
	},
	{
		id: "13",
		date: "2021-01-12",
		amount: 350,
		type: "expense",
		category: "healthcare",
		description: "Doctor visit",
	},
	{
		id: "14",
		date: "2021-01-13",
		amount: 1000,
		type: "expense",
		category: "rent",
		description: "Monthly rent",
	},
	{
		id: "15",
		date: "2021-01-14",
		amount: 200,
		type: "expense",
		category: "groceries",
		description: "Weekly groceries",
	},
];
